# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tanx_app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "app.py"]

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tanx_test
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "unittest", "test_app.py"]
    depends_on:
      - app
